config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :users
  resources :discord_bots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :discord_bot
end

app/models/discord_bot.rb
class DiscordBot < ApplicationRecord
  validates :song_name, :artist, presence: true

  has_many :chats
  has_many :users, through: :chats

  def song_and_artist
    "#{self.song_name} by #{self.artist}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :chats
  has_many :discord_bots, through: :chats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def new
    @chat = Chat.new
    @discord_bots = DiscordBot.all
    @users = User.all
  end

  def create
    @chat = Chat.create(params.require(:chat).permit(:name, :discord_bot_id, :user_id))
    redirect_to user_path(@chat.user)
  end
end

app/controllers/discord_bots_controller.rb
class DiscordBotsController < ApplicationController

  def index
    @discord_bots = DiscordBot.all
  end

  def show
    @discord_bot = DiscordBot.find(params[:id])
  end

  def new
    @discord_bot = DiscordBot.new
  end

  def create
    @discord_bot = DiscordBot.create(params.require(:discord_bot).permit(:song_name, :artist))
    redirect_to discord_bot_path(@discord_bot)
  end

  def edit
    @discord_bot = DiscordBot.find(params[:id])
  end

  def update
    @discord_bot = DiscordBot.find(params[:id])
    @discord_bot.update(params.require(:discord_bot).permit(:song_name, :artist))
    redirect_to discord_bot_path(@discord_bot)
  end

  def destroy 
    @discord_bot = DiscordBot.find(params[:id])
    @discord_bot.destroy
    redirect_to discord_bots_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @chat = Chat.new
    @discord_bots = DiscordBot.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:name, :username, :online))
    redirect_to user_path(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(params.require(:user).permit(:name, :username, :online))
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/discord_bots_helper.rb
module DiscordBotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/new.html.erb
<h1>Make a new Chat</h1>

<%= form_for @chat do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :discord_bot_id %>
  <%= f.collection_select :discord_bot_id, @discord_bots, :id, :song_name %>

  <%= f.label :user_id %>
  <%= f.collection_select :user_id, @users, :id, :name %>

  <%= f.submit %>

<% end %>

app/views/discord_bots/edit.html.erb
<h1>Edit this bot</h1>

<%= form_for @discord_bot do |f| %>

  <%= f.label :song_name %>
  <%= f.text_field :song_name %>

  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%= f.submit %>

<% end %>

app/views/discord_bots/index.html.erb
<h1>All of Ricky's Discord Song Bots Here</h1>

<%= button_to "Create a new Discord Song Bot here", new_discord_bot_path, method: :get %>

<% @discord_bots.each do |bot| %>
  <p>
    <%= button_to "#{bot.song_name} by #{bot.artist}", discord_bot_path(bot), method: :get %>
  </p>
<% end %>

app/views/discord_bots/new.html.erb
<h1>Create a new discord song bot</h1>

<%= form_for @discord_bot do |f| %>

  <%= f.label :song_name %>
  <%= f.text_field :song_name %>

  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%= f.submit %>

<% end %>

app/views/discord_bots/show.html.erb
<h1>More information about <%= @discord_bot.song_name %> by <%= @discord_bot.artist %> </h1>

<p>
  <%= button_to "Go back to see all the discord music bots", discord_bots_path, method: :get %>
</p>

<p>
  <%= button_to "Edit this discord music bot", edit_discord_bot_path, method: :get %>
</p>

<p>
  <%= button_to "Destroy this discord music bot", discord_bot_path, method: :delete %>
</p>

<p>
  Song name: <%= @discord_bot.song_name %>
</p>

<p>
  Artist: <%= @discord_bot.artist %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiscordBotSongsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.css' %>

  </head>

  <body>
    <div class="container">
      <div><% if flash[:notice] %>
        <div><%= flash[:notice] %></div>
      <% end %> <%= yield %></div>
    </div>

    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
    <%= javascript_include_tag 'https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js' %>

  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit the user here</h1>

<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :online %>
  <%= f.check_box :online %>

  <%= f.submit %>

<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<%= button_to "Create a new user", new_user_path, method: :get %>

<% @users.each do |user| %>
  <p>
    <%= button_to user.username, user_path(user), method: :get %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Create a new user</h1>

<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :online %>
  <%= f.check_box :online %>

  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h1>More information about <%= @user.username %> (Who's actually <%= @user.name %> IRL ) </h1>

<p>
<%= button_to "Go back to see all the users", users_path, method: :get %>
</p>
<p>
<%= button_to "Edit this user", edit_user_path, method: :get %>
</p>
<p>
<%= button_to "Delete this user", user_path(@user), method: :delete %>
</p>

<p>
  Name: <%= @user.name %>
</p>

<p>
  Username: <%= @user.username %>
</p>

<p>
  Online: <%= @user.online %>
</p>

<br>

<h1>Make a new chat here</h1>

<%= form_for @chat do |f| %>

  <%= f.hidden_field :user_id, value: @user.id %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :discord_bot_id %>
  <%= f.collection_select :discord_bot_id, @discord_bots, :id, :song_and_artist %>
  <br>

  <%= f.submit %>

<% end %>

<h1>All the chats associated with this user</h1>

<% @user.chats.each do |chat| %>

  <p>
    <%= "#{chat.name}: #{@user.username} is listening to #{chat.discord_bot.song_name} by #{chat.discord_bot.artist}" %>
  </p>

<% end %>